In [1]:
import numpy as np

In [3]:
np.__version__

'2.4.4'

## Create and Read

### 1D Array

In [11]:
arr1 = np.array([1, 2, 3, 4, 5, 6])
arr1

array([1, 2, 3, 4, 5, 6])

In [12]:
type(arr1)

numpy.ndarray

In [13]:
arr1.shape

(6,)

In [14]:
arr1.dtype

dtype('int64')

In [15]:
arr1.ndim

1

In [16]:
arr1.size

6

###  2D Array

In [26]:
arr2 = np.array([[1, 4, 5], [6, 7 ,4]])
arr2

array([[1, 4, 5],
       [6, 7, 4]])

In [27]:
arr2.ndim

2

In [28]:
arr2.shape # Row, Col

(2, 3)

In [29]:
arr2.dtype

dtype('int64')

In [30]:
arr2.size

6

### 3D Array

In [37]:
arr3 = np.array([[[1, 4, 5], [6, 7 ,4]], [[3, 5, 4], [5, 8, 7]], [[1, 4, 5], [6, 7 ,4]]])
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [38]:
arr3.ndim

3

In [39]:
arr3.shape # (Number of layers - how many 2D array it has, rows, cols)

(3, 2, 3)

In [40]:
arr3.size

18

### Create random array

In [50]:
randomArr = np.random.rand(3, 2, 3)
randomArr

array([[[0.87155418, 0.4298067 , 0.94362232],
        [0.78189853, 0.39596574, 0.37155553]],

       [[0.68501305, 0.8881631 , 0.64517739],
        [0.77080099, 0.4701439 , 0.92925505]],

       [[0.23127666, 0.52222161, 0.79321285],
        [0.81877431, 0.72452126, 0.10694452]]])

In [51]:
randomArr.dtype

dtype('float64')

In [52]:
zeros = np.zeros((3, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [53]:
zeros.ndim

3

In [56]:
full = np.full((3, 2, 3), 9)
full

array([[[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]]])